version: '3.8'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    container_name: django
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: api_local_django
    volumes:
      - ..:/workspaces/app:cached
    environment:
      - DJANGO_SECRET_KEY=supersecretkey
      - USE_DOCKER=yes
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=api
      - POSTGRES_USER=PGUSER
      - POSTGRES_PASSWORD=PGPW123
      - DATABASE_URL=postgres://PGUSER:PGPW123@localhost:5432/api
    command: sleep infinity
    network_mode: service:postgres
    user: vscode

  postgres:
    container_name: postgres
    image: postgres:11.3
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=api
      - POSTGRES_USER=PGUSER
      - POSTGRES_PASSWORD=PGPW123
    ports:
      - "5432:5432"
      - "8000:8000"
